---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bmad-studio-pdb
  namespace: bmad-studio
  labels:
    app: bmad-studio
    environment: production
    managed-by: terraform
  annotations:
    description: "Pod Disruption Budget for BMAD Studio to ensure high availability"
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: bmad-studio
      version: v1.0.0
---
apiVersion: policy/v1
kind: PodSecurityPolicy
metadata:
  name: bmad-studio-psp
  labels:
    app: bmad-studio
    environment: production
    security-policy: enterprise
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1001
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1001
        max: 65535
  seLinux:
    rule: 'RunAsAny'
  seccompProfile:
    type: 'RuntimeDefault'
  forbiddenSysctls:
    - '*'
---
apiVersion: v1
kind: LimitRange
metadata:
  name: bmad-studio-limits
  namespace: bmad-studio
  labels:
    app: bmad-studio
    environment: production
spec:
  limits:
  - type: Container
    default:
      cpu: 500m
      memory: 1Gi
      ephemeral-storage: 2Gi
    defaultRequest:
      cpu: 250m
      memory: 512Mi
      ephemeral-storage: 1Gi
    min:
      cpu: 100m
      memory: 256Mi
      ephemeral-storage: 512Mi
    max:
      cpu: 2000m
      memory: 4Gi
      ephemeral-storage: 8Gi
  - type: Pod
    max:
      cpu: 4000m
      memory: 8Gi
      ephemeral-storage: 16Gi
  - type: PersistentVolumeClaim
    min:
      storage: 1Gi
    max:
      storage: 100Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: bmad-studio-quota
  namespace: bmad-studio
  labels:
    app: bmad-studio
    environment: production
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    requests.storage: 100Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    pods: "50"
    replicationcontrollers: "20"
    resourcequotas: "1"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"
    services.nodeports: "0"
    count/deployments.apps: "10"
    count/replicasets.apps: "20"
    count/statefulsets.apps: "5"
    count/cronjobs.batch: "5"
    count/jobs.batch: "10"