---
apiVersion: v1
kind: Secret
metadata:
  name: bmad-studio-secrets
  namespace: bmad-studio
  labels:
    app: bmad-studio
    environment: production
    managed-by: terraform
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "bmad-studio"
    vault.hashicorp.com/agent-inject-secret-database: "secret/data/bmad-studio/database"
    vault.hashicorp.com/agent-inject-template-database: |
      {{- with secret "secret/data/bmad-studio/database" -}}
      DB_USERNAME={{ .Data.data.username }}
      DB_PASSWORD={{ .Data.data.password }}
      {{- end }}
    vault.hashicorp.com/agent-inject-secret-redis: "secret/data/bmad-studio/redis"
    vault.hashicorp.com/agent-inject-template-redis: |
      {{- with secret "secret/data/bmad-studio/redis" -}}
      REDIS_PASSWORD={{ .Data.data.password }}
      REDIS_AUTH_TOKEN={{ .Data.data.auth_token }}
      {{- end }}
    vault.hashicorp.com/agent-inject-secret-app: "secret/data/bmad-studio/app"
    vault.hashicorp.com/agent-inject-template-app: |
      {{- with secret "secret/data/bmad-studio/app" -}}
      JWT_SECRET={{ .Data.data.jwt_secret }}
      API_KEY={{ .Data.data.api_key }}
      ENCRYPTION_KEY={{ .Data.data.encryption_key }}
      {{- end }}
type: Opaque
data:
  # Placeholder values - will be replaced by Vault injection
  DB_USERNAME: cGxhY2Vob2xkZXI=  # placeholder
  DB_PASSWORD: cGxhY2Vob2xkZXI=  # placeholder
  REDIS_PASSWORD: cGxhY2Vob2xkZXI=  # placeholder
  JWT_SECRET: cGxhY2Vob2xkZXI=  # placeholder
---
apiVersion: v1
kind: Secret
metadata:
  name: bmad-studio-tls
  namespace: bmad-studio
  labels:
    app: bmad-studio
    environment: production
    managed-by: cert-manager
type: kubernetes.io/tls
data:
  # TLS certificate and key will be managed by cert-manager
  tls.crt: ""
  tls.key: ""