---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bmad-studio-sa
  namespace: bmad-studio
  labels:
    app: bmad-studio
    environment: production
    managed-by: terraform
  annotations:
    description: "Service account for BMAD Studio application"
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bmad-studio-role
  namespace: bmad-studio
  labels:
    app: bmad-studio
    environment: production
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bmad-studio-rolebinding
  namespace: bmad-studio
  labels:
    app: bmad-studio
    environment: production
subjects:
- kind: ServiceAccount
  name: bmad-studio-sa
  namespace: bmad-studio
roleRef:
  kind: Role
  name: bmad-studio-role
  apiGroup: rbac.authorization.k8s.io