/* eslint-env jest */
// Generated by BMAD Studio Template
// Basic test setup

const { main } = require('../src/index');

describe('Application Entry Point', () => {
  test('should run main function without errors', () => {
    // Capture console output
    const consoleSpy = jest.spyOn(console, 'log').mockImplementation();

    main();

    expect(consoleSpy).toHaveBeenCalledWith('✅ BMAD Studio project is ready for development');
    expect(consoleSpy).toHaveBeenCalledWith('💡 Use *agent bmad-orchestrator to get started');

    consoleSpy.mockRestore();
  });
});
