// Generated by BMAD Studio Template
// Entry point for your application

console.log('🚀 Application started with BMAD Studio Template');

// TODO: Implement your main application logic here
// This file serves as the entry point for your project

const main = () => {
  console.log('✅ BMAD Studio project is ready for development');
  console.log('💡 Use *agent bmad-orchestrator to get started');
};

if (require.main === module) {
  main();
}

module.exports = { main };
